### ISSUE TITLE
TLS fixes

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/java-http#16]
Re-work the HTTPS code. 

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/2614
- https://github.com/FusionAuth/fusionauth-issues/issues/2498

**Comment by robotdan** [comment]
Branch
- https://github.com/FusionAuth/java-http/tree/bpontarelli/tls-fixes

**Comment by voidmain** [comment]
This is fixed by the PR: https://github.com/FusionAuth/java-http/pull/17 and released in 0.3.0.
