### ISSUE TITLE
account for non ASCII values in the headers or preamble

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/java-http#25]
I think we should probably treat these values as opaque instead of throwing out the request. 

- https://www.rfc-editor.org/rfc/rfc8187
- https://www.rfc-editor.org/rfc/rfc7230#section-3.2.4

Specifically in RFC 7230, section 3.2.4

> Historically, HTTP has allowed field content with text in the
   ISO-8859-1 charset [[ISO-8859-1](https://www.rfc-editor.org/rfc/rfc7230#ref-ISO-8859-1)], supporting other charsets only
   through use of [[RFC2047](https://www.rfc-editor.org/rfc/rfc2047)] encoding.  In practice, most HTTP header
   field values use only a subset of the US-ASCII charset [[USASCII](https://www.rfc-editor.org/rfc/rfc7230#ref-USASCII)].
   Newly defined header fields SHOULD limit their field values to
   US-ASCII octets.  A recipient SHOULD treat other octets in field
   content (obs-text) as opaque data.

So it seems the most appropriate option is to treat them as opaque and allow it. From testing, this looks to be how Netty and Tomcat handle this.

**Comment by mmanes** [comment]
Fixed in 0.3.5.
